---
http_interactions:
- request:
    method: get
    uri: http://diufvm31.unifr.ch:8090/CyberCoachServer/resources/partnerships/partner1;partner2
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 07 Dec 2015 17:31:01 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(8.1.6.v20120903)
    body:
      encoding: UTF-8
      string: '{"uri":"/CyberCoachServer/resources/partnerships/partner1;partner2/","id":10869,"userconfirmed1":true,"userconfirmed2":true,"datecreated":1449507961211,"publicvisible":2,"user1":{"uri":"/CyberCoachServer/resources/users/partner1/","username":"partner1"},"user2":{"uri":"/CyberCoachServer/resources/users/partner2/","username":"partner2"}}'
    http_version: 
  recorded_at: Mon, 07 Dec 2015 17:38:25 GMT
- request:
    method: get
    uri: http://partner1:password@diufvm31.unifr.ch:8090/CyberCoachServer/resources/authenticateduser/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 07 Dec 2015 17:31:01 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(8.1.6.v20120903)
    body:
      encoding: UTF-8
      string: '{"uri":"/CyberCoachServer/resources/users/partner1/","username":"partner1","password":"*","realname":"Partner
        1","email":"partner@email.com","datecreated":1449507777103,"publicvisible":2}'
    http_version: 
  recorded_at: Mon, 07 Dec 2015 17:38:25 GMT
- request:
    method: get
    uri: http://partner1:password@diufvm31.unifr.ch:8090/CyberCoachServer/resources/partnerships/partner1;partner2
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 07 Dec 2015 17:31:01 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(8.1.6.v20120903)
    body:
      encoding: UTF-8
      string: '{"uri":"/CyberCoachServer/resources/partnerships/partner1;partner2/","id":10869,"userconfirmed1":true,"userconfirmed2":true,"datecreated":1449507961211,"publicvisible":2,"user1":{"uri":"/CyberCoachServer/resources/users/partner1/","username":"partner1"},"user2":{"uri":"/CyberCoachServer/resources/users/partner2/","username":"partner2"}}'
    http_version: 
  recorded_at: Mon, 07 Dec 2015 17:38:25 GMT
recorded_with: VCR 2.9.3
