---
http_interactions:
- request:
    method: get
    uri: http://user321:@diufvm31.unifr.ch:8090/CyberCoachServer/resources/users/user321?size=20&start=0
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 11 Dec 2015 19:16:47 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(8.1.6.v20120903)
    body:
      encoding: UTF-8
      string: '{"uri":"/CyberCoachServer/resources/users/user321/","username":"user321","password":"*","realname":"Real
        User","email":"user@test.rs","datecreated":1448741688000,"publicvisible":2,"partnerships":[{"uri":"/CyberCoachServer/resources/partnerships/user123;user321/","id":9349}]}'
    http_version: 
  recorded_at: Fri, 11 Dec 2015 19:24:38 GMT
recorded_with: VCR 2.9.3
